[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm install",
  "cd apps/api && npm install"
]

[phases.build]
cmds = [
  "cd apps/api",
  "npx prisma generate --schema=./prisma/schema.prisma",
  "npm run build"
]

[start]
cmd = "cd apps/api && node dist/main.js"
